apiVersion: v1
kind: Service
metadata:
  name: simplycs-co-nz-nginx-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: simplycs-co-nz-nginx
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30004